starting_dir = "."
author = "Christian"
excludes = [
  "**/node_modules/*",
  "**/vendor/*",
  "go.sum",
  "yarn.lock",
  "package-lock.json",
  "pnpm-lock.yaml",
  "**/dist/*",
  "**/build/*",
  "**/.git/*",
  "**/.idea/*",
  "**/mocks/*",
  "*.csv",
  "*.pdf",
  "*.doc",
  "*.docx",
  "*.json",
  "*.png",
  "*.jpg",
  "*.jpeg",
  "*.gif",
  "*.svg",
  "*.ico",
  "*.woff",
  "*.woff2",
  "*.ttf",
  "*.eot",
  ".DS_Store",
  "Thumbs.db",
  ".vscode/*",
  "*.log",
  ".gitignore",
  "*.bak",
  "*.swp",
  "*.swo",
  "*.tmp",
  "*.temp",
  "*.o",
  "*.out",
  "*.jar",
  "*.war",
  "*.ear",
  ".pytest_cache/*",
  "db.sqlite3",
  ".next/*",
  ".cache/*",
  "__pycache__/*",
]
